language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e . --use-mirrors"
 - "pip install coverage coveralls --use-mirrors"
script: coverage run setup.py test
after_success:
 - coveralls
