language: python
sudo: true
cache: pip
python:
 - "2.7"
before_install:
  # downgrade ES to the version we use: http://docs.travis-ci.com/user/database-setup/#Using-a-specific-version-of-ElasticSearch
  - "curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.deb && sudo dpkg -i --force-confnew elasticsearch-0.90.5.deb"
  - "sudo service elasticsearch start"
  - "sleep 10"
  - "curl http://localhost:9200/"  # print ES info
install:
 - "uname -a"
 - "lsb_release -a"
 - "couchdb -V"
 - "curl http://127.0.0.1:5984/"
 - "redis-cli ping"
 - "psql -c 'create database pillowtop' -U postgres"
 - "pip install -e . --process-dependency-links"
 - "pip install coverage coveralls"
script: coverage run manage.py test
after_success:
 - coveralls
services:
  - postgresql
  - couchdb
  - redis-server
