language: python
python:
 - "2.6"
 - "2.7"
install:
 - "sudo apt-get install libevent-dev"
 - "pip install -e ."
 - "psql -c 'create database fluff_test' -U postgres"
 - "pip install coverage coveralls"
script:
 - "coverage run setup.py test"
after_success:
 - coverage report
 - coveralls

