language: python
python:
 - "2.6"
git:
  submodules: false
install:
 - "sudo add-apt-repository -y ppa:ieltonf/ppa"
 - "sudo apt-get update"
 - "sudo apt-get install parallel"
 - "bash -ex .travis/get-submodules.sh"
 - "bash -e .travis/quietly-run-install.sh"
 - "bash -e .travis/quietly-install-requirements.sh"
 - "cp .travis/localsettings.py localsettings.py"
script: python manage.py test --noinput
services:
 - postgresql
 - couchdb
 - rabbitmq
 - elasticsearch
 - memcache
