language: python
python:
 - "2.6"
git:
  submodules: false
install:
 - "sh -ex .travis/get-submodules.sh"
 - "sh -ex install.sh"
 - "pip install -r requirements/requirements.txt"
 - "pip install -r requirements/dev-requirements.txt"
script: python manage.py test --no-input
services:
 - postgresql
 - couchdb
 - rabbitmq
 - elasticsearch
