language: python
sudo: required
branches:
  only:
    - master
env:
  matrix:
    - MATRIX_TYPE=javascript BOWER=yes NODE=yes DOCKER=yes
    # need node installs for app_manager.XpathValidatorTest
    - MATRIX_TYPE=python TESTRUNNER=testrunner.GroupTestRunnerCatchall BOWER=yes NODE=yes DOCKER=yes
    - MATRIX_TYPE=python TESTRUNNER=testrunner.GroupTestRunner0 DOCKER=yes
before_install:
  - "./dockerhq.sh travis build"
  - "./dockerhq.sh travis up -d"
  - "./dockerhq.sh travis ps"
script: './dockerhq.sh travis run -e CUSTOMSETTINGS="docker.localsettings_docker_sharded" web_test python manage.py test form_processor'
services:
  - docker
