language: python
python:
 - "2.6"
git:
  submodules: false
install:
 - "bash -ex .travis/get-submodules.sh"
 - "bash -e .travis/quietly-run-install.sh"
 - "bash -e .travis/quietly-install-requirements.sh"
script: python manage.py test --noinput
services:
 - postgresql
 - couchdb
 - rabbitmq
 - elasticsearch
