language: python
python:
 - "2.7"
install:
 - "uname -a"
 - "lsb_release -a"
 - "bash -ex .travis/upgrade-couchdb.sh"
 - "curl http://127.0.0.1:5984/"
 - "psql -c 'create database pillowtop' -U postgres"
 - "pip install -e ."
 - "pip install coverage coveralls"
script: coverage run `which django-admin.py` test --settings settings
after_success:
 - coveralls
services:
  - postgresql
  - couchdb
  - redis-server
