language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true
python:
  - "2.7"
env:
  global:
    - CFLAGS=-O0
    - COUCHDB_USER=""
    - COUCHDB_PW=""
    - TRAVIS_INSTALL="y"
  matrix:
    - MATRIX_TYPE=python TESTRUNNER=testrunner.GroupTestRunnerCatchall
    - MATRIX_TYPE=python TESTRUNNER=testrunner.GroupTestRunner0
    - MATRIX_TYPE=javascript
branches:
  only:
    - master
before_install:
  - "curl http://localhost:5984/"  # print couch info
  - "uname -a"
  - "lsb_release -a"
addons:
  apt:
    packages:
    - moreutils
    - libblas-dev
    - liblapack-dev
before_install:
  - "git clone https://github.com/dimagi/commcarehq-venv.git"
  - "cp -r commcarehq-venv/hq_env/* ~/virtualenv/"
  - "source ~/virtualenv/bin/activate"
install:
  - "bash -e .travis/misc-setup.sh"
  - "curl -X PUT http://localhost:5984/commcarehq_test"  # this is an auth test
  - "bash -e scripts/uninstall-requirements.sh"
  - "time (pip install --exists-action w -r requirements/requirements.txt --use-mirrors --timeout 60)"
  - "cp .travis/localsettings.py localsettings.py"
script: "bash -e .travis/matrix-runner.sh"
after_success:
  - coverage report
  - coveralls
services:
  - postgresql
  - couchdb
  - redis-server
