language: python
python:
 - "2.6"
env:
 - CFLAGS=-O0
branches:
  only:
   - master
install:
 - "uname -a"
 - "lsb_release -a"
 - "sudo apt-get install moreutils"
 - "bash -ex .travis/upgrade-couchdb.sh | ts"
 - "git clone https://github.com/dimagi/commcarehq-venv.git"
 - "time (bash -e .travis/quietly-run-install.sh | ts)"
 - "commcarehq-venv/hq_env/bin/pip install -r requirements/requirements.txt -r requirements/dev-requirements.txt --use-mirrors"
 - "time (bash -e .travis/misc-setup.sh | ts)"
 - "cp .travis/localsettings.py localsettings.py"
 - "commcarehq-venv/hq_env/bin/pip install coveralls coverage unittest2 mock"
script: "cat .travis/apps_under_test | grep -v '^#' | xargs commcarehq-venv/hq_env/bin/coverage run manage.py test --noinput --failfast | ts"
after_success:
 - coveralls
services:
 - postgresql
 - couchdb
 - rabbitmq
 - elasticsearch
 - memcache
