language: python
env:
 - DJANGO_SETTINGS_MODULE=settings
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install pytz requests simplejson mock unittest2"
 - "pip install coverage coveralls"
 - "pip install git+https://github.com/dimagi/xml2json"
script: "coverage run `which django-admin.py` test --traceback couchforms --verbosity 2"
after_success:
 - coveralls
services:
 - couchdb
 - redis-server
