language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install coverage django-coverage"
script: django-admin.py test --settings settings --traceback case phone
services:
 - couchdb
