language: python
#sudo: required
branches:
  only:
    - master
env:
  matrix:
    - TEST=javascript
    # need node installs for app_manager.XpathValidatorTest
    - TEST=python NOSE_DIVIDED_WE_RUN=05 JS=yes
    - TEST=python NOSE_DIVIDED_WE_RUN=6a JS=yes
    - TEST=python NOSE_DIVIDED_WE_RUN=bf JS=yes
    - TEST=python-sharded
script: "scripts/docker test"
after_success:
  - coverage report
  - coveralls
services:
  - docker
