language: python
python:
 - "2.6"
env:
 - CFLAGS=-O0
branches:
  only:
   - master
install:
 - "uname -a"
 - "lsb_release -a"
 - "bash -ex .travis/upgrade-couchdb.sh"
 - "curl http://127.0.0.1:5984/"
 - "git clone https://github.com/dimagi/commcarehq-venv.git"
 - ". commcarehq-venv/hq_env/bin/activate"
 - "time bash -e .travis/quietly-run-install.sh"
 - "time pip install -r requirements/requirements.txt -r requirements/dev-requirements.txt --use-mirrors"
 - "bash -e .travis/misc-setup.sh"
 - "cp .travis/localsettings.py localsettings.py"
 - "pip install coveralls coverage unittest2 mock"
script: "cat .travis/apps_under_test | grep -v '^#' | xargs coverage run manage.py test --noinput --failfast"
after_success:
 - coveralls
services:
 - postgresql
 - couchdb
 - rabbitmq
 - elasticsearch
 - memcache
