language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install coverage"
before_script:
 - "gem install travis-artifacts"
script: coverage run setup.py test
after_script:
 - "coverage html"
 - "travis-artifacts upload --path coverage-report --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
 - "echo See full coverage report at http://travis-artifacts.dimagi.com.s3-website-us-east-1.amazonaws.com/artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID/index.html"
 - "coverage report"
env:
 global:
  - "ARTIFACTS_AWS_REGION=us-east-1" 
  - "ARTIFACTS_S3_BUCKET=travis-artifacts.dimagi.com"
  - secure: "JbCPNtDj7nSbmNaF7vZ8e2JX9nxvVgUYB74MCuGsSRV3ckN9WtXL81bWhoFm\nFPE/ClVKfY0gqAtahOrzixBUuEeh4Kz2OVAsHeo6ldfAZOauEqGgkSlC+8yE\nnMFlEnd/yjIvl59ElSJxRVou2KAfZgWK1MaFSHzDkCMfcfhm6Do="
  - secure: "AjK6O+gAiCczZjbhJQ3AcRkC77YCpc8ZAntENulM+Tzjsq+rtyJGFO0i2JzI\n9qmJFrKIMxqZHHJIfW6EqfJcnA9yncsa1GMsmGnYCyS6GGU0ASDVWKUKVScy\nPP9xtGtcZj5rzgaGx2x7qEnHNxEZekG0WcbnKLMhciwwLm1RtX0="

