language: python
python:
 - "2.6"
 - "2.7"
install:
 - "sudo apt-get install libfreetype6 libfreetype6-dev zlib1g-dev libpng12-dev zlib1g"
 - "sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib"
 - "sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib"
 - "pip install -e . --use-mirrors"
 - "pip install coverage coveralls --use-mirrors"
 - "pip install unittest2 mock"
script: coverage run `which django-admin.py` test --settings settings --traceback utils
after_success:
 - coveralls
services:
 - couchdb