language: python
sudo: required
branches:
  only:
    - master
before_install:
  - "./dockerhq.sh travis build"
  - "./dockerhq.sh travis up -d"
  - "./dockerhq.sh travis ps"
script: './dockerhq.sh travis run -e CUSTOMSETTINGS="docker.localsettings_docker_sharded" web_test python manage.py test form_processor'
services:
  - docker
