language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install coverage coveralls"
script: coverage run `which django-admin.py` test --settings settings --traceback case phone
after_success:
 - coveralls
 - coverage report
services:
 - couchdb
