postgres:
  image: postgres:9.4
  environment:
    POSTGRES_USER: commcarehq
    POSTGRES_PASSWORD: commcarehq
  volumes:
    - /var/lib/postgresql:/var/lib/postgresql
couch:
  image: klaemo/couchdb:latest
  volumes:
    - /var/lib/couchdb:/usr/local/var/lib/couchdb
  ports:
    - "5984:5984"
redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch:1.7.4
  ports:
    - "9200:9200"
  volumes:
    - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
vendor:
  image: python:2.7
  working_dir: /mnt
  volumes:
    - .:/mnt
  environment:
    PYTHONUSERBASE: /mnt/vendor
  command: pip install -r requirements/requirements.txt -r requirements/dev-requirements.txt --user --upgrade
web:
  build: .
  dockerfile: Dockerfile_dev
  working_dir: /mnt
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/mnt
  ports:
    - "8000:8000"
  environment:
    PYTHONUSERBASE: /mnt/vendor
  links:
    - postgres
    - couch
    - redis
    - elasticsearch
    - vendor
