postres:
  image: postgres:9.4
  environment:
    POSTGRES_USER: commcarehq
    POSTGRES_PASSWORD: commcarehq
couch:
  image: klaemo/couchdb:latest
  volumes:
    - /var/lib/couchdb:/usr/local/var/lib/couchdb
  ports:
    - "5984:5984"
redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch:1.7.4
  ports:
    - "9200:9200"
  volumes:
    - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
web:
  build: .
  dockerfile: Dockerfile_dev
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
