postgres:
  extends:
    file: hq-compose.yml
    service: postgres
  ports:
    - "5432:5432"

couch:
  extends:
    file: hq-compose.yml
    service: couch
  ports:
    - "5984:5984"

redis:
  extends:
    file: hq-compose.yml
    service: redis
  ports:
    - "6379:6379"

elasticsearch:
  extends:
    file: hq-compose.yml
    service: elasticsearch
  ports:
    - "9200:9200"

kafka:
  extends:
    file: hq-compose.yml
    service: kafka
  ports:
    - "2181:2181"
    - "9092:9092"

riakcs:
  extends:
    file: hq-compose.yml
    service: riakcs
  ports:
    # bind to host port 9880 since 8080 is commonly used for other services
    - "9880:8080"
    - "8098:8098"
