postgres:
  extends:
    file: hq-compose.yml
    service: postgres
  ports:
    - "5432:5432"

couch:
  extends:
    file: hq-compose.yml
    service: couch
  ports:
    - "5984:5984"

redis:
  extends:
    file: hq-compose.yml
    service: redis
  ports:
    - "6379:6379"

elasticsearch:
  extends:
    file: hq-compose.yml
    service: elasticsearch
  command: elasticsearch --cluster.name=${ES_CLUSTER_NAME}
  environment:
    - ES_CLUSTER_NAME
  ports:
    - "9200:9200"

kafka:
  extends:
    file: hq-compose.yml
    service: kafka
  ports:
    - "2181:2181"
    - "9092:9092"

riakcs:
  extends:
    file: hq-compose.yml
    service: riakcs
  ports:
    - "9980:9980"
    - "8098:8098"
