trunk: master
name: autostaging
branches:
  - explicit_case_processing
  - auto-gps+schedule
  - auto-gps
  - schedule # SK 7/17
  - es_none_type # Emord 8/4
#  - add-build-ui
  - hq-dropdown # sravan 5/7
  - refactor-domain-copy2  # Brian 5/20
  - logos # Nick P 5/28
  - vellum-requirejs # Daniel 6/12
  - emwf-refactor  # Ethan 8/06
  - real-project-spaces # Nick P 7/27
  - archive-to-deactivate  # cz 7/30
  - subscription-no-contact-info # bb 8/4
#  - cachecomparisons  # SK 8/11
  - opm  # Ethan 8/11
  - increase-es-timeout # Nick P 8/11
submodules:
  submodules/couchlog-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/django-soil-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/formdesigner:
#    branches:
#      - develop-staging # Daniel 6/12 (major refactor + itemsets?)
#      - universal-analytics-upgrade # Nick P 7/8
  submodules/formtranslate-src:
    branches:
      - static-tags # Nick P 5/20
      # Danny 8/12. If form validation seems wonky on staging, just remove this
      - clean-up-api
  submodules/touchforms-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/dimagi-utils-src:
#    branches:
#      - json_response-status
  submodules/pillowtop-src:
    branches:
      - reset # SK 7/28
#  corehq/apps/hqmedia/static/hqmedia/MediaUploader:
#    branches:
#      - 124289-fix-mm-uploads-in-ff # Daniel 8/7
  submodules/dimagi-utils-src:
    branches:
      # Danny 8/12. If there's weird errors or issues in saving forms
      # or saving apps, just remove this
      - faster-lazy-attachments
