- title: 'Basic'
  settings:
    - hq.name  # Name
    - hq.application_version # App Version (disabled)
    # Application
#    - hq.is_j2me
#    - hq.is_odk
    - hq.case_sharing  # Case Sharing
    - hq.cloudcare_enabled  # CloudCare Enabled
    - hq.use_custom_suite
    - hq.custom_suite
    # RemoteApp
    - hq.profile_url
    - hq.manage_urls

- title: General Settings
  settings:
    - features.sense  # CommCare Sense
    - properties.cc-autoup-freq  # Auto Update Frequency
    - properties.unsent-number-limit  # Unsent Form Limit
    - properties.server-tether  # Sync Mode
    - properties.cc-autosync-freq  # Auto-Sync Frequency
    - properties.unsent-time-limit  # Unsynced Time Limit
    - properties.cc-content-valid  # Multimedia Validation
    - properties.password_format  # Password Format

- title: 'J2ME UI Settings'
  settings:
    - properties.extra_key_action  # Extra Key Action
    - properties.cc-entry-mode  # Item Selection Mode
    - properties.cc-send-unsent  # Send Forms Mode
#    - hq.success_message  # Success Message  # depends on properties.cc-send-unsent
    - hq.text_input  # Text Input
    - properties.ViewStyle  # Form Entry Style
    - properties.cc-user-mode  # User Login Mode

- title: 'J2ME CommCare Properties'
  settings:
    - hq.build_spec  # CommCare Version
    - hq.platform  # J2ME Platform
    - hq.admin_password  # Admin Password
    - hq.show_user_registration  # Allow User Registration from Phone
    - properties.cc-send-procedure  # Send Data

- title: 'Advanced (Logging)'
  settings:
    - properties.logenabled  # Logging Enabled
    - properties.log_prop_weekly  # Weekly Log Sending Frequency
    - properties.log_prop_daily  # Daily Log Sending Frequency

- title: 'Disabled'
  always_show: false
  settings:
    - properties.purge-freq  # Purge Frequency (disabled)
    - properties.user_reg_server  # Server User Registration (disabled)
    - properties.restore-tolerance  # OTA Restore Tolerance (disabled)
    - features.users  # No Users Mode (disabled)
    - properties.loose_media  # Loose Media Mode (disabled)
    - properties.cc-review-days  # Days for Review (disabled)